-- Seed data for biomarker_standards table
-- Contains ~100 common biomarkers with US conventional units

-- Clear existing data (for re-seeding)
TRUNCATE TABLE public.biomarker_standards CASCADE;

-- ============================================================================
-- METABOLIC PANEL
-- ============================================================================

INSERT INTO public.biomarker_standards (code, name, aliases, category, standard_unit, unit_conversions, reference_ranges, description, clinical_significance, decimal_places, display_order) VALUES
('glucose_fasting', 'Fasting Blood Glucose',
  ARRAY['blood glucose', 'fasting glucose', 'FBG', 'blood sugar', 'fasting blood sugar', 'serum glucose'],
  'metabolic', 'mg/dL',
  '{"mmol/L": 18.0182}'::jsonb,
  '{"male": {"low": 70, "high": 100}, "female": {"low": 70, "high": 100}}'::jsonb,
  'Measures blood sugar level after fasting for at least 8 hours',
  'High levels may indicate diabetes or prediabetes. Low levels may indicate hypoglycemia.',
  0, 10),

('hba1c', 'Hemoglobin A1C',
  ARRAY['A1C', 'HbA1c', 'glycated hemoglobin', 'glycohemoglobin', 'hemoglobin A1c'],
  'metabolic', '%',
  '{}'::jsonb,
  '{"male": {"low": 4.0, "high": 5.6}, "female": {"low": 4.0, "high": 5.6}}'::jsonb,
  'Average blood sugar over the past 2-3 months',
  'Used to diagnose and monitor diabetes. Values 5.7-6.4% indicate prediabetes, ≥6.5% indicates diabetes.',
  1, 11),

('insulin', 'Insulin',
  ARRAY['fasting insulin', 'serum insulin'],
  'metabolic', 'uIU/mL',
  '{"pmol/L": 0.1439}'::jsonb,
  '{"male": {"low": 2.6, "high": 24.9}, "female": {"low": 2.6, "high": 24.9}}'::jsonb,
  'Hormone that regulates blood sugar',
  'High levels with normal glucose may indicate insulin resistance.',
  1, 12),

-- ============================================================================
-- LIPID PANEL
-- ============================================================================

('cholesterol_total', 'Total Cholesterol',
  ARRAY['cholesterol', 'serum cholesterol', 'total chol'],
  'lipid_panel', 'mg/dL',
  '{"mmol/L": 38.67}'::jsonb,
  '{"male": {"low": 125, "high": 200}, "female": {"low": 125, "high": 200}}'::jsonb,
  'Total amount of cholesterol in the blood',
  'High levels increase cardiovascular disease risk.',
  0, 20),

('ldl_cholesterol', 'LDL Cholesterol',
  ARRAY['LDL', 'LDL-C', 'bad cholesterol', 'low-density lipoprotein'],
  'lipid_panel', 'mg/dL',
  '{"mmol/L": 38.67}'::jsonb,
  '{"male": {"low": 0, "high": 100}, "female": {"low": 0, "high": 100}}'::jsonb,
  'Low-density lipoprotein cholesterol',
  'High LDL is associated with increased cardiovascular disease risk.',
  0, 21),

('hdl_cholesterol', 'HDL Cholesterol',
  ARRAY['HDL', 'HDL-C', 'good cholesterol', 'high-density lipoprotein'],
  'lipid_panel', 'mg/dL',
  '{"mmol/L": 38.67}'::jsonb,
  '{"male": {"low": 40, "high": 200}, "female": {"low": 50, "high": 200}}'::jsonb,
  'High-density lipoprotein cholesterol',
  'Higher levels are protective against heart disease.',
  0, 22),

('triglycerides', 'Triglycerides',
  ARRAY['TG', 'trigs', 'serum triglycerides'],
  'lipid_panel', 'mg/dL',
  '{"mmol/L": 88.57}'::jsonb,
  '{"male": {"low": 0, "high": 150}, "female": {"low": 0, "high": 150}}'::jsonb,
  'Type of fat found in blood',
  'High levels increase heart disease and pancreatitis risk.',
  0, 23),

('vldl_cholesterol', 'VLDL Cholesterol',
  ARRAY['VLDL', 'VLDL-C', 'very low-density lipoprotein'],
  'lipid_panel', 'mg/dL',
  '{"mmol/L": 38.67}'::jsonb,
  '{"male": {"low": 5, "high": 40}, "female": {"low": 5, "high": 40}}'::jsonb,
  'Very low-density lipoprotein cholesterol',
  'Carries triglycerides; high levels indicate cardiovascular risk.',
  0, 24),

('non_hdl_cholesterol', 'Non-HDL Cholesterol',
  ARRAY['non-HDL', 'non HDL-C'],
  'lipid_panel', 'mg/dL',
  '{"mmol/L": 38.67}'::jsonb,
  '{"male": {"low": 0, "high": 130}, "female": {"low": 0, "high": 130}}'::jsonb,
  'Total cholesterol minus HDL cholesterol',
  'Better predictor of cardiovascular risk than LDL alone.',
  0, 25),

-- ============================================================================
-- COMPLETE BLOOD COUNT (CBC)
-- ============================================================================

('wbc', 'White Blood Cell Count',
  ARRAY['WBC', 'leukocytes', 'white blood cells', 'white cell count'],
  'cbc', 'K/uL',
  '{"10^9/L": 1, "x10^9/L": 1, "cells/uL": 0.001}'::jsonb,
  '{"male": {"low": 4.5, "high": 11.0}, "female": {"low": 4.5, "high": 11.0}}'::jsonb,
  'Number of white blood cells per unit of blood',
  'High levels may indicate infection or inflammation; low levels may indicate immune problems.',
  1, 30),

('rbc', 'Red Blood Cell Count',
  ARRAY['RBC', 'erythrocytes', 'red blood cells', 'red cell count'],
  'cbc', 'M/uL',
  '{"10^12/L": 1, "x10^12/L": 1}'::jsonb,
  '{"male": {"low": 4.5, "high": 5.5}, "female": {"low": 4.0, "high": 5.0}}'::jsonb,
  'Number of red blood cells per unit of blood',
  'Low levels indicate anemia; high levels may indicate polycythemia.',
  2, 31),

('hemoglobin', 'Hemoglobin',
  ARRAY['Hgb', 'Hb', 'haemoglobin'],
  'cbc', 'g/dL',
  '{"g/L": 0.1, "mmol/L": 1.611}'::jsonb,
  '{"male": {"low": 13.5, "high": 17.5}, "female": {"low": 12.0, "high": 16.0}}'::jsonb,
  'Oxygen-carrying protein in red blood cells',
  'Low levels indicate anemia; high levels may indicate dehydration or lung disease.',
  1, 32),

('hematocrit', 'Hematocrit',
  ARRAY['Hct', 'HCT', 'packed cell volume', 'PCV'],
  'cbc', '%',
  '{}'::jsonb,
  '{"male": {"low": 38.3, "high": 48.6}, "female": {"low": 35.5, "high": 44.9}}'::jsonb,
  'Percentage of blood volume occupied by red blood cells',
  'Low levels indicate anemia; high levels may indicate dehydration.',
  1, 33),

('mcv', 'Mean Corpuscular Volume',
  ARRAY['MCV', 'mean cell volume'],
  'cbc', 'fL',
  '{}'::jsonb,
  '{"male": {"low": 80, "high": 100}, "female": {"low": 80, "high": 100}}'::jsonb,
  'Average size of red blood cells',
  'High values indicate macrocytic anemia; low values indicate microcytic anemia.',
  1, 34),

('mch', 'Mean Corpuscular Hemoglobin',
  ARRAY['MCH'],
  'cbc', 'pg',
  '{}'::jsonb,
  '{"male": {"low": 27, "high": 33}, "female": {"low": 27, "high": 33}}'::jsonb,
  'Average amount of hemoglobin per red blood cell',
  'Helps classify types of anemia.',
  1, 35),

('mchc', 'Mean Corpuscular Hemoglobin Concentration',
  ARRAY['MCHC'],
  'cbc', 'g/dL',
  '{}'::jsonb,
  '{"male": {"low": 32, "high": 36}, "female": {"low": 32, "high": 36}}'::jsonb,
  'Average concentration of hemoglobin in red blood cells',
  'Low values indicate hypochromic anemia.',
  1, 36),

('rdw', 'Red Cell Distribution Width',
  ARRAY['RDW', 'RDW-CV'],
  'cbc', '%',
  '{}'::jsonb,
  '{"male": {"low": 11.5, "high": 14.5}, "female": {"low": 11.5, "high": 14.5}}'::jsonb,
  'Variation in red blood cell size',
  'High values may indicate mixed anemia or nutritional deficiency.',
  1, 37),

('platelets', 'Platelet Count',
  ARRAY['PLT', 'thrombocytes', 'platelet count'],
  'cbc', 'K/uL',
  '{"10^9/L": 1, "x10^9/L": 1}'::jsonb,
  '{"male": {"low": 150, "high": 400}, "female": {"low": 150, "high": 400}}'::jsonb,
  'Number of platelets per unit of blood',
  'Low levels increase bleeding risk; high levels increase clotting risk.',
  0, 38),

('mpv', 'Mean Platelet Volume',
  ARRAY['MPV'],
  'cbc', 'fL',
  '{}'::jsonb,
  '{"male": {"low": 7.5, "high": 11.5}, "female": {"low": 7.5, "high": 11.5}}'::jsonb,
  'Average size of platelets',
  'May indicate bone marrow function.',
  1, 39),

('neutrophils', 'Neutrophils',
  ARRAY['NEUT', 'neutrophil count', 'absolute neutrophil count', 'ANC'],
  'cbc', 'K/uL',
  '{"10^9/L": 1}'::jsonb,
  '{"male": {"low": 1.8, "high": 7.7}, "female": {"low": 1.8, "high": 7.7}}'::jsonb,
  'Type of white blood cell that fights bacteria',
  'Low levels increase infection risk; high levels may indicate infection.',
  1, 40),

('lymphocytes', 'Lymphocytes',
  ARRAY['LYMPH', 'lymphocyte count', 'absolute lymphocyte count'],
  'cbc', 'K/uL',
  '{"10^9/L": 1}'::jsonb,
  '{"male": {"low": 1.0, "high": 4.8}, "female": {"low": 1.0, "high": 4.8}}'::jsonb,
  'Type of white blood cell important for immune response',
  'High levels may indicate viral infection; low levels may indicate immune deficiency.',
  1, 41),

('monocytes', 'Monocytes',
  ARRAY['MONO', 'monocyte count'],
  'cbc', 'K/uL',
  '{"10^9/L": 1}'::jsonb,
  '{"male": {"low": 0.2, "high": 0.8}, "female": {"low": 0.2, "high": 0.8}}'::jsonb,
  'Type of white blood cell that becomes macrophages',
  'High levels may indicate chronic inflammation or infection.',
  1, 42),

('eosinophils', 'Eosinophils',
  ARRAY['EOS', 'eosinophil count'],
  'cbc', 'K/uL',
  '{"10^9/L": 1}'::jsonb,
  '{"male": {"low": 0.0, "high": 0.4}, "female": {"low": 0.0, "high": 0.4}}'::jsonb,
  'Type of white blood cell involved in allergic responses',
  'High levels may indicate allergies, parasites, or autoimmune disease.',
  1, 43),

('basophils', 'Basophils',
  ARRAY['BASO', 'basophil count'],
  'cbc', 'K/uL',
  '{"10^9/L": 1}'::jsonb,
  '{"male": {"low": 0.0, "high": 0.1}, "female": {"low": 0.0, "high": 0.1}}'::jsonb,
  'Type of white blood cell involved in allergic reactions',
  'High levels may indicate allergic reactions or certain blood disorders.',
  2, 44),

-- ============================================================================
-- LIVER FUNCTION
-- ============================================================================

('alt', 'Alanine Aminotransferase',
  ARRAY['ALT', 'SGPT', 'alanine transaminase'],
  'liver', 'IU/L',
  '{"U/L": 1}'::jsonb,
  '{"male": {"low": 7, "high": 56}, "female": {"low": 7, "high": 45}}'::jsonb,
  'Enzyme found primarily in the liver',
  'High levels may indicate liver damage or disease.',
  0, 50),

('ast', 'Aspartate Aminotransferase',
  ARRAY['AST', 'SGOT', 'aspartate transaminase'],
  'liver', 'IU/L',
  '{"U/L": 1}'::jsonb,
  '{"male": {"low": 10, "high": 40}, "female": {"low": 9, "high": 32}}'::jsonb,
  'Enzyme found in liver and heart',
  'High levels may indicate liver or heart damage.',
  0, 51),

('alp', 'Alkaline Phosphatase',
  ARRAY['ALP', 'alk phos', 'alkaline phos'],
  'liver', 'IU/L',
  '{"U/L": 1}'::jsonb,
  '{"male": {"low": 44, "high": 147}, "female": {"low": 44, "high": 147}}'::jsonb,
  'Enzyme found in liver, bones, and other tissues',
  'High levels may indicate liver or bone disease.',
  0, 52),

('ggt', 'Gamma-Glutamyl Transferase',
  ARRAY['GGT', 'GGTP', 'gamma GT'],
  'liver', 'IU/L',
  '{"U/L": 1}'::jsonb,
  '{"male": {"low": 9, "high": 48}, "female": {"low": 9, "high": 36}}'::jsonb,
  'Enzyme found in liver and bile ducts',
  'Elevated levels may indicate liver disease or alcohol use.',
  0, 53),

('bilirubin_total', 'Total Bilirubin',
  ARRAY['bilirubin', 'total bili', 'T. Bili'],
  'liver', 'mg/dL',
  '{"umol/L": 0.0585}'::jsonb,
  '{"male": {"low": 0.1, "high": 1.2}, "female": {"low": 0.1, "high": 1.2}}'::jsonb,
  'Breakdown product of red blood cells',
  'High levels cause jaundice and may indicate liver or gallbladder problems.',
  1, 54),

('bilirubin_direct', 'Direct Bilirubin',
  ARRAY['conjugated bilirubin', 'D. Bili', 'direct bili'],
  'liver', 'mg/dL',
  '{"umol/L": 0.0585}'::jsonb,
  '{"male": {"low": 0.0, "high": 0.3}, "female": {"low": 0.0, "high": 0.3}}'::jsonb,
  'Processed bilirubin ready for excretion',
  'High levels may indicate bile duct obstruction.',
  1, 55),

('albumin', 'Albumin',
  ARRAY['serum albumin', 'ALB'],
  'liver', 'g/dL',
  '{"g/L": 0.1}'::jsonb,
  '{"male": {"low": 3.5, "high": 5.5}, "female": {"low": 3.5, "high": 5.5}}'::jsonb,
  'Main protein made by the liver',
  'Low levels may indicate liver disease, malnutrition, or kidney disease.',
  1, 56),

('total_protein', 'Total Protein',
  ARRAY['serum protein', 'TP'],
  'liver', 'g/dL',
  '{"g/L": 0.1}'::jsonb,
  '{"male": {"low": 6.0, "high": 8.3}, "female": {"low": 6.0, "high": 8.3}}'::jsonb,
  'Total amount of protein in blood',
  'Abnormal levels may indicate liver, kidney, or bone marrow problems.',
  1, 57),

('globulin', 'Globulin',
  ARRAY['serum globulin'],
  'liver', 'g/dL',
  '{"g/L": 0.1}'::jsonb,
  '{"male": {"low": 2.0, "high": 3.5}, "female": {"low": 2.0, "high": 3.5}}'::jsonb,
  'Group of proteins including antibodies',
  'High levels may indicate chronic inflammation or infection.',
  1, 58),

('ag_ratio', 'Albumin/Globulin Ratio',
  ARRAY['A/G ratio', 'A:G'],
  'liver', 'ratio',
  '{}'::jsonb,
  '{"male": {"low": 1.0, "high": 2.5}, "female": {"low": 1.0, "high": 2.5}}'::jsonb,
  'Ratio of albumin to globulin',
  'Abnormal ratio may indicate liver or kidney disease.',
  1, 59),

-- ============================================================================
-- KIDNEY FUNCTION
-- ============================================================================

('creatinine', 'Creatinine',
  ARRAY['serum creatinine', 'creat'],
  'kidney', 'mg/dL',
  '{"umol/L": 0.0113}'::jsonb,
  '{"male": {"low": 0.7, "high": 1.3}, "female": {"low": 0.6, "high": 1.1}}'::jsonb,
  'Waste product from muscle metabolism',
  'High levels may indicate kidney dysfunction.',
  2, 60),

('bun', 'Blood Urea Nitrogen',
  ARRAY['BUN', 'urea nitrogen', 'urea'],
  'kidney', 'mg/dL',
  '{"mmol/L": 2.801}'::jsonb,
  '{"male": {"low": 7, "high": 20}, "female": {"low": 7, "high": 20}}'::jsonb,
  'Waste product from protein metabolism',
  'High levels may indicate kidney problems or dehydration.',
  0, 61),

('bun_creatinine_ratio', 'BUN/Creatinine Ratio',
  ARRAY['BUN:Creatinine', 'B/C ratio'],
  'kidney', 'ratio',
  '{}'::jsonb,
  '{"male": {"low": 10, "high": 20}, "female": {"low": 10, "high": 20}}'::jsonb,
  'Ratio of BUN to creatinine',
  'Helps distinguish between kidney and other causes of elevated BUN.',
  0, 62),

('egfr', 'Estimated GFR',
  ARRAY['eGFR', 'estimated glomerular filtration rate', 'GFR'],
  'kidney', 'mL/min/1.73m2',
  '{}'::jsonb,
  '{"male": {"low": 90, "high": 120}, "female": {"low": 90, "high": 120}}'::jsonb,
  'Estimate of how well kidneys filter blood',
  'Values below 60 indicate chronic kidney disease; below 15 indicates kidney failure.',
  0, 63),

('uric_acid', 'Uric Acid',
  ARRAY['serum uric acid', 'urate'],
  'kidney', 'mg/dL',
  '{"umol/L": 0.0168}'::jsonb,
  '{"male": {"low": 3.4, "high": 7.0}, "female": {"low": 2.4, "high": 6.0}}'::jsonb,
  'Waste product from purine metabolism',
  'High levels may cause gout or kidney stones.',
  1, 64),

('cystatin_c', 'Cystatin C',
  ARRAY['CysC'],
  'kidney', 'mg/L',
  '{}'::jsonb,
  '{"male": {"low": 0.5, "high": 1.0}, "female": {"low": 0.5, "high": 1.0}}'::jsonb,
  'Protein used to estimate kidney function',
  'More accurate kidney function marker than creatinine in some populations.',
  2, 65),

-- ============================================================================
-- ELECTROLYTES
-- ============================================================================

('sodium', 'Sodium',
  ARRAY['Na', 'serum sodium', 'Na+'],
  'electrolyte', 'mEq/L',
  '{"mmol/L": 1}'::jsonb,
  '{"male": {"low": 136, "high": 145}, "female": {"low": 136, "high": 145}}'::jsonb,
  'Essential electrolyte for nerve and muscle function',
  'Abnormal levels can affect brain function and cause confusion.',
  0, 70),

('potassium', 'Potassium',
  ARRAY['K', 'serum potassium', 'K+'],
  'electrolyte', 'mEq/L',
  '{"mmol/L": 1}'::jsonb,
  '{"male": {"low": 3.5, "high": 5.0}, "female": {"low": 3.5, "high": 5.0}}'::jsonb,
  'Essential electrolyte for heart and muscle function',
  'Abnormal levels can cause dangerous heart rhythms.',
  1, 71),

('chloride', 'Chloride',
  ARRAY['Cl', 'serum chloride', 'Cl-'],
  'electrolyte', 'mEq/L',
  '{"mmol/L": 1}'::jsonb,
  '{"male": {"low": 98, "high": 106}, "female": {"low": 98, "high": 106}}'::jsonb,
  'Essential electrolyte for fluid balance',
  'Abnormal levels often accompany sodium abnormalities.',
  0, 72),

('bicarbonate', 'Bicarbonate',
  ARRAY['CO2', 'carbon dioxide', 'HCO3', 'total CO2'],
  'electrolyte', 'mEq/L',
  '{"mmol/L": 1}'::jsonb,
  '{"male": {"low": 22, "high": 29}, "female": {"low": 22, "high": 29}}'::jsonb,
  'Buffer that helps maintain blood pH',
  'Abnormal levels may indicate acid-base imbalance or kidney problems.',
  0, 73),

('calcium', 'Calcium',
  ARRAY['Ca', 'serum calcium', 'Ca2+', 'total calcium'],
  'electrolyte', 'mg/dL',
  '{"mmol/L": 4.008}'::jsonb,
  '{"male": {"low": 8.6, "high": 10.2}, "female": {"low": 8.6, "high": 10.2}}'::jsonb,
  'Essential mineral for bones, muscles, and nerves',
  'Abnormal levels can affect bones, kidneys, and heart.',
  1, 74),

('calcium_ionized', 'Ionized Calcium',
  ARRAY['iCa', 'free calcium', 'ionized Ca'],
  'electrolyte', 'mg/dL',
  '{"mmol/L": 4.008}'::jsonb,
  '{"male": {"low": 4.6, "high": 5.3}, "female": {"low": 4.6, "high": 5.3}}'::jsonb,
  'Active form of calcium in blood',
  'More accurate measure of calcium status than total calcium.',
  1, 75),

('magnesium', 'Magnesium',
  ARRAY['Mg', 'serum magnesium', 'Mg2+'],
  'electrolyte', 'mg/dL',
  '{"mmol/L": 2.431}'::jsonb,
  '{"male": {"low": 1.7, "high": 2.2}, "female": {"low": 1.7, "high": 2.2}}'::jsonb,
  'Essential mineral for muscle and nerve function',
  'Low levels can cause muscle cramps, weakness, and heart rhythm problems.',
  1, 76),

('phosphorus', 'Phosphorus',
  ARRAY['phosphate', 'PO4', 'serum phosphorus', 'inorganic phosphorus'],
  'electrolyte', 'mg/dL',
  '{"mmol/L": 3.097}'::jsonb,
  '{"male": {"low": 2.5, "high": 4.5}, "female": {"low": 2.5, "high": 4.5}}'::jsonb,
  'Essential mineral for bones and energy metabolism',
  'Abnormal levels may indicate kidney disease or bone problems.',
  1, 77),

-- ============================================================================
-- THYROID PANEL
-- ============================================================================

('tsh', 'Thyroid Stimulating Hormone',
  ARRAY['TSH', 'thyrotropin'],
  'thyroid', 'mIU/L',
  '{"uIU/mL": 1}'::jsonb,
  '{"male": {"low": 0.4, "high": 4.0}, "female": {"low": 0.4, "high": 4.0}}'::jsonb,
  'Hormone that stimulates thyroid gland',
  'High TSH indicates hypothyroidism; low TSH indicates hyperthyroidism.',
  2, 80),

('t4_free', 'Free T4',
  ARRAY['FT4', 'free thyroxine', 'thyroxine free'],
  'thyroid', 'ng/dL',
  '{"pmol/L": 0.0777}'::jsonb,
  '{"male": {"low": 0.8, "high": 1.8}, "female": {"low": 0.8, "high": 1.8}}'::jsonb,
  'Active form of thyroxine hormone',
  'Low levels with high TSH confirm hypothyroidism.',
  2, 81),

('t4_total', 'Total T4',
  ARRAY['T4', 'thyroxine'],
  'thyroid', 'mcg/dL',
  '{"nmol/L": 0.0777}'::jsonb,
  '{"male": {"low": 4.5, "high": 12.5}, "female": {"low": 4.5, "high": 12.5}}'::jsonb,
  'Total thyroxine in blood',
  'Affected by binding protein levels.',
  1, 82),

('t3_free', 'Free T3',
  ARRAY['FT3', 'free triiodothyronine'],
  'thyroid', 'pg/mL',
  '{"pmol/L": 0.651}'::jsonb,
  '{"male": {"low": 2.3, "high": 4.2}, "female": {"low": 2.3, "high": 4.2}}'::jsonb,
  'Active form of triiodothyronine',
  'Most metabolically active thyroid hormone.',
  1, 83),

('t3_total', 'Total T3',
  ARRAY['T3', 'triiodothyronine'],
  'thyroid', 'ng/dL',
  '{"nmol/L": 0.0154}'::jsonb,
  '{"male": {"low": 80, "high": 200}, "female": {"low": 80, "high": 200}}'::jsonb,
  'Total triiodothyronine in blood',
  'May be elevated in early hyperthyroidism.',
  0, 84),

('thyroid_peroxidase_ab', 'Thyroid Peroxidase Antibodies',
  ARRAY['TPO Ab', 'anti-TPO', 'TPO antibodies'],
  'thyroid', 'IU/mL',
  '{}'::jsonb,
  '{"male": {"low": 0, "high": 34}, "female": {"low": 0, "high": 34}}'::jsonb,
  'Antibodies against thyroid enzyme',
  'Elevated levels indicate autoimmune thyroid disease (Hashimoto''s).',
  0, 85),

-- ============================================================================
-- VITAMINS & NUTRIENTS
-- ============================================================================

('vitamin_d', 'Vitamin D, 25-Hydroxy',
  ARRAY['25-OH vitamin D', '25-hydroxyvitamin D', 'vitamin D total', 'calcidiol'],
  'vitamin', 'ng/mL',
  '{"nmol/L": 0.4}'::jsonb,
  '{"male": {"low": 30, "high": 100}, "female": {"low": 30, "high": 100}}'::jsonb,
  'Primary form of vitamin D in blood',
  'Low levels increase risk of bone disease and may affect immune function.',
  0, 90),

('vitamin_b12', 'Vitamin B12',
  ARRAY['B12', 'cobalamin', 'cyanocobalamin'],
  'vitamin', 'pg/mL',
  '{"pmol/L": 0.738}'::jsonb,
  '{"male": {"low": 200, "high": 900}, "female": {"low": 200, "high": 900}}'::jsonb,
  'Essential vitamin for nerve function and blood cell formation',
  'Low levels can cause anemia and neurological problems.',
  0, 91),

('folate', 'Folate',
  ARRAY['folic acid', 'vitamin B9', 'serum folate'],
  'vitamin', 'ng/mL',
  '{"nmol/L": 0.4417}'::jsonb,
  '{"male": {"low": 2.7, "high": 17.0}, "female": {"low": 2.7, "high": 17.0}}'::jsonb,
  'B vitamin important for cell division',
  'Low levels can cause anemia; important during pregnancy.',
  1, 92),

('vitamin_b1', 'Vitamin B1',
  ARRAY['thiamine', 'thiamin'],
  'vitamin', 'nmol/L',
  '{}'::jsonb,
  '{"male": {"low": 70, "high": 180}, "female": {"low": 70, "high": 180}}'::jsonb,
  'Essential vitamin for energy metabolism',
  'Deficiency can cause beriberi and Wernicke''s encephalopathy.',
  0, 93),

('vitamin_b6', 'Vitamin B6',
  ARRAY['pyridoxine', 'pyridoxal phosphate'],
  'vitamin', 'ng/mL',
  '{"nmol/L": 4.046}'::jsonb,
  '{"male": {"low": 5, "high": 50}, "female": {"low": 5, "high": 50}}'::jsonb,
  'Important for protein metabolism and immune function',
  'Deficiency can cause anemia and neurological symptoms.',
  1, 94),

('vitamin_a', 'Vitamin A',
  ARRAY['retinol'],
  'vitamin', 'mcg/dL',
  '{"umol/L": 0.0349}'::jsonb,
  '{"male": {"low": 38, "high": 98}, "female": {"low": 28, "high": 86}}'::jsonb,
  'Fat-soluble vitamin for vision and immune function',
  'Deficiency causes night blindness; excess is toxic.',
  0, 95),

('vitamin_e', 'Vitamin E',
  ARRAY['alpha-tocopherol', 'tocopherol'],
  'vitamin', 'mg/L',
  '{"umol/L": 0.43}'::jsonb,
  '{"male": {"low": 5.5, "high": 17}, "female": {"low": 5.5, "high": 17}}'::jsonb,
  'Antioxidant vitamin',
  'Deficiency is rare but can cause nerve problems.',
  1, 96),

-- ============================================================================
-- IRON STUDIES
-- ============================================================================

('iron', 'Serum Iron',
  ARRAY['Fe', 'iron level', 'serum Fe'],
  'iron', 'mcg/dL',
  '{"umol/L": 5.587}'::jsonb,
  '{"male": {"low": 60, "high": 170}, "female": {"low": 40, "high": 150}}'::jsonb,
  'Amount of iron circulating in blood',
  'Low levels indicate iron deficiency; high levels may indicate iron overload.',
  0, 100),

('ferritin', 'Ferritin',
  ARRAY['serum ferritin'],
  'iron', 'ng/mL',
  '{"ug/L": 1, "pmol/L": 0.0448}'::jsonb,
  '{"male": {"low": 24, "high": 336}, "female": {"low": 11, "high": 307}}'::jsonb,
  'Iron storage protein',
  'Best indicator of iron stores; low levels indicate deficiency.',
  0, 101),

('tibc', 'Total Iron-Binding Capacity',
  ARRAY['TIBC', 'total iron binding capacity'],
  'iron', 'mcg/dL',
  '{"umol/L": 5.587}'::jsonb,
  '{"male": {"low": 250, "high": 400}, "female": {"low": 250, "high": 400}}'::jsonb,
  'Capacity of blood to bind iron',
  'High TIBC indicates iron deficiency.',
  0, 102),

('transferrin_saturation', 'Transferrin Saturation',
  ARRAY['iron saturation', 'TSAT', 'transferrin sat'],
  'iron', '%',
  '{}'::jsonb,
  '{"male": {"low": 20, "high": 50}, "female": {"low": 15, "high": 50}}'::jsonb,
  'Percentage of transferrin bound to iron',
  'Low values indicate iron deficiency; high values indicate overload.',
  0, 103),

-- ============================================================================
-- INFLAMMATION MARKERS
-- ============================================================================

('crp', 'C-Reactive Protein',
  ARRAY['CRP', 'C-reactive protein'],
  'inflammation', 'mg/L',
  '{"mg/dL": 10}'::jsonb,
  '{"male": {"low": 0, "high": 3.0}, "female": {"low": 0, "high": 3.0}}'::jsonb,
  'Marker of acute inflammation',
  'High levels indicate infection or inflammation.',
  1, 110),

('hscrp', 'High-Sensitivity CRP',
  ARRAY['hs-CRP', 'hsCRP', 'cardio CRP'],
  'inflammation', 'mg/L',
  '{"mg/dL": 10}'::jsonb,
  '{"male": {"low": 0, "high": 1.0}, "female": {"low": 0, "high": 1.0}}'::jsonb,
  'Sensitive marker for low-grade inflammation',
  'Used to assess cardiovascular risk.',
  2, 111),

('esr', 'Erythrocyte Sedimentation Rate',
  ARRAY['ESR', 'sed rate', 'sedimentation rate'],
  'inflammation', 'mm/hr',
  '{}'::jsonb,
  '{"male": {"low": 0, "high": 15}, "female": {"low": 0, "high": 20}}'::jsonb,
  'Non-specific marker of inflammation',
  'Elevated in many inflammatory conditions.',
  0, 112),

('homocysteine', 'Homocysteine',
  ARRAY['Hcy', 'plasma homocysteine'],
  'inflammation', 'umol/L',
  '{}'::jsonb,
  '{"male": {"low": 4, "high": 15}, "female": {"low": 4, "high": 12}}'::jsonb,
  'Amino acid linked to cardiovascular risk',
  'High levels associated with increased heart disease risk.',
  1, 113),

-- ============================================================================
-- HORMONES
-- ============================================================================

('testosterone_total', 'Total Testosterone',
  ARRAY['testosterone', 'serum testosterone'],
  'hormone', 'ng/dL',
  '{"nmol/L": 0.0347}'::jsonb,
  '{"male": {"low": 300, "high": 1000}, "female": {"low": 15, "high": 70}}'::jsonb,
  'Primary male sex hormone',
  'Low levels in men can cause fatigue, low libido, and muscle loss.',
  0, 120),

('testosterone_free', 'Free Testosterone',
  ARRAY['free T', 'bioavailable testosterone'],
  'hormone', 'pg/mL',
  '{"pmol/L": 0.0347}'::jsonb,
  '{"male": {"low": 50, "high": 200}, "female": {"low": 0.5, "high": 5}}'::jsonb,
  'Unbound, active form of testosterone',
  'Better indicator of testosterone activity than total.',
  1, 121),

('estradiol', 'Estradiol',
  ARRAY['E2', 'estrogen'],
  'hormone', 'pg/mL',
  '{"pmol/L": 0.272}'::jsonb,
  '{"male": {"low": 10, "high": 40}, "female": {"low": 15, "high": 350}}'::jsonb,
  'Primary female sex hormone',
  'Varies with menstrual cycle; important for bone health.',
  0, 122),

('progesterone', 'Progesterone',
  ARRAY['P4'],
  'hormone', 'ng/mL',
  '{"nmol/L": 0.318}'::jsonb,
  '{"male": {"low": 0.1, "high": 0.8}, "female": {"low": 0.1, "high": 25}}'::jsonb,
  'Hormone important for menstrual cycle and pregnancy',
  'Levels vary greatly with menstrual cycle.',
  1, 123),

('dhea_s', 'DHEA-Sulfate',
  ARRAY['DHEA-S', 'DHEAS', 'dehydroepiandrosterone sulfate'],
  'hormone', 'mcg/dL',
  '{"umol/L": 0.0271}'::jsonb,
  '{"male": {"low": 80, "high": 560}, "female": {"low": 35, "high": 430}}'::jsonb,
  'Precursor to sex hormones',
  'Declines with age; low levels may indicate adrenal insufficiency.',
  0, 124),

('cortisol', 'Cortisol',
  ARRAY['serum cortisol', 'AM cortisol'],
  'hormone', 'mcg/dL',
  '{"nmol/L": 0.0362}'::jsonb,
  '{"male": {"low": 6.2, "high": 19.4}, "female": {"low": 6.2, "high": 19.4}}'::jsonb,
  'Stress hormone produced by adrenal glands',
  'High levels may indicate Cushing''s; low levels may indicate Addison''s.',
  1, 125),

('fsh', 'Follicle Stimulating Hormone',
  ARRAY['FSH'],
  'hormone', 'mIU/mL',
  '{"IU/L": 1}'::jsonb,
  '{"male": {"low": 1.5, "high": 12.4}, "female": {"low": 3.5, "high": 150}}'::jsonb,
  'Hormone that stimulates egg/sperm production',
  'High levels in women may indicate menopause.',
  1, 126),

('lh', 'Luteinizing Hormone',
  ARRAY['LH'],
  'hormone', 'mIU/mL',
  '{"IU/L": 1}'::jsonb,
  '{"male": {"low": 1.7, "high": 8.6}, "female": {"low": 2.4, "high": 96}}'::jsonb,
  'Hormone that triggers ovulation/testosterone production',
  'Varies with menstrual cycle; surge indicates ovulation.',
  1, 127),

('prolactin', 'Prolactin',
  ARRAY['PRL'],
  'hormone', 'ng/mL',
  '{"ug/L": 1}'::jsonb,
  '{"male": {"low": 4, "high": 15}, "female": {"low": 4, "high": 23}}'::jsonb,
  'Hormone that stimulates milk production',
  'High levels can cause infertility and may indicate pituitary tumor.',
  1, 128),

('growth_hormone', 'Growth Hormone',
  ARRAY['GH', 'HGH', 'somatotropin'],
  'hormone', 'ng/mL',
  '{"ug/L": 1}'::jsonb,
  '{"male": {"low": 0.0, "high": 3.0}, "female": {"low": 0.0, "high": 8.0}}'::jsonb,
  'Hormone important for growth and metabolism',
  'Levels vary throughout the day; pulsatile secretion.',
  1, 129),

('igf_1', 'Insulin-Like Growth Factor 1',
  ARRAY['IGF-1', 'somatomedin C'],
  'hormone', 'ng/mL',
  '{}'::jsonb,
  '{"male": {"low": 115, "high": 355}, "female": {"low": 115, "high": 355}}'::jsonb,
  'Marker of growth hormone activity',
  'More stable than GH; used to diagnose GH disorders.',
  0, 130),

-- ============================================================================
-- CARDIAC MARKERS
-- ============================================================================

('bnp', 'B-Type Natriuretic Peptide',
  ARRAY['BNP', 'brain natriuretic peptide'],
  'cardiac', 'pg/mL',
  '{"ng/L": 1}'::jsonb,
  '{"male": {"low": 0, "high": 100}, "female": {"low": 0, "high": 100}}'::jsonb,
  'Hormone released when heart is stressed',
  'High levels indicate heart failure.',
  0, 140),

('nt_probnp', 'NT-proBNP',
  ARRAY['N-terminal proBNP', 'pro-BNP'],
  'cardiac', 'pg/mL',
  '{"ng/L": 1}'::jsonb,
  '{"male": {"low": 0, "high": 125}, "female": {"low": 0, "high": 125}}'::jsonb,
  'Fragment of BNP prohormone',
  'More stable than BNP for diagnosing heart failure.',
  0, 141),

('troponin_i', 'Troponin I',
  ARRAY['cTnI', 'cardiac troponin I'],
  'cardiac', 'ng/mL',
  '{"ug/L": 1}'::jsonb,
  '{"male": {"low": 0, "high": 0.04}, "female": {"low": 0, "high": 0.04}}'::jsonb,
  'Protein released when heart muscle is damaged',
  'Elevated levels indicate heart attack or heart muscle injury.',
  3, 142),

('troponin_t', 'Troponin T',
  ARRAY['cTnT', 'cardiac troponin T'],
  'cardiac', 'ng/mL',
  '{"ug/L": 1}'::jsonb,
  '{"male": {"low": 0, "high": 0.01}, "female": {"low": 0, "high": 0.01}}'::jsonb,
  'Protein released when heart muscle is damaged',
  'Elevated levels indicate heart attack or heart muscle injury.',
  3, 143),

('ldh', 'Lactate Dehydrogenase',
  ARRAY['LDH', 'lactic acid dehydrogenase'],
  'cardiac', 'IU/L',
  '{"U/L": 1}'::jsonb,
  '{"male": {"low": 140, "high": 280}, "female": {"low": 140, "high": 280}}'::jsonb,
  'Enzyme found in many tissues',
  'Elevated in many conditions including heart attack, liver disease, and cancer.',
  0, 144),

('ck', 'Creatine Kinase',
  ARRAY['CK', 'CPK', 'creatine phosphokinase'],
  'cardiac', 'IU/L',
  '{"U/L": 1}'::jsonb,
  '{"male": {"low": 55, "high": 170}, "female": {"low": 30, "high": 135}}'::jsonb,
  'Enzyme found in heart and muscle',
  'Elevated after heart attack or muscle injury.',
  0, 145),

('ck_mb', 'CK-MB',
  ARRAY['CK MB', 'creatine kinase MB'],
  'cardiac', 'ng/mL',
  '{"ug/L": 1}'::jsonb,
  '{"male": {"low": 0, "high": 5}, "female": {"low": 0, "high": 5}}'::jsonb,
  'Heart-specific form of creatine kinase',
  'Elevated after heart attack.',
  1, 146),

('lp_a', 'Lipoprotein(a)',
  ARRAY['Lp(a)', 'lipoprotein a'],
  'cardiac', 'mg/dL',
  '{"nmol/L": 0.4}'::jsonb,
  '{"male": {"low": 0, "high": 30}, "female": {"low": 0, "high": 30}}'::jsonb,
  'Genetic risk factor for cardiovascular disease',
  'High levels (>30 mg/dL) increase heart disease risk independent of LDL.',
  0, 147),

('apob', 'Apolipoprotein B',
  ARRAY['ApoB', 'apo B'],
  'cardiac', 'mg/dL',
  '{"g/L": 100}'::jsonb,
  '{"male": {"low": 50, "high": 130}, "female": {"low": 50, "high": 130}}'::jsonb,
  'Protein found on LDL particles',
  'May be better predictor of heart disease than LDL cholesterol.',
  0, 148),

-- ============================================================================
-- TUMOR MARKERS
-- ============================================================================

('psa', 'Prostate-Specific Antigen',
  ARRAY['PSA', 'total PSA', 'prostate specific antigen'],
  'tumor_marker', 'ng/mL',
  '{"ug/L": 1}'::jsonb,
  '{"male": {"low": 0, "high": 4.0}, "female": {"low": 0, "high": 0}}'::jsonb,
  'Protein produced by prostate gland',
  'Elevated in prostate cancer, BPH, and prostatitis. Screening utility debated.',
  2, 150),

('psa_free', 'Free PSA',
  ARRAY['free PSA', 'fPSA'],
  'tumor_marker', 'ng/mL',
  '{"ug/L": 1}'::jsonb,
  '{"male": {"low": 0, "high": 4.0}, "female": {"low": 0, "high": 0}}'::jsonb,
  'Unbound fraction of PSA',
  'Free/total PSA ratio helps differentiate cancer from BPH. Higher ratio suggests BPH.',
  2, 151),

('afp', 'Alpha-Fetoprotein',
  ARRAY['AFP', 'alpha fetoprotein'],
  'tumor_marker', 'ng/mL',
  '{"ug/L": 1, "IU/mL": 0.83}'::jsonb,
  '{"male": {"low": 0, "high": 10}, "female": {"low": 0, "high": 10}}'::jsonb,
  'Oncofetal protein marker',
  'Elevated in hepatocellular carcinoma, germ cell tumors, and pregnancy.',
  1, 152),

('cea', 'Carcinoembryonic Antigen',
  ARRAY['CEA'],
  'tumor_marker', 'ng/mL',
  '{"ug/L": 1}'::jsonb,
  '{"male": {"low": 0, "high": 3.0}, "female": {"low": 0, "high": 3.0}}'::jsonb,
  'Oncofetal antigen',
  'Used to monitor colorectal cancer. Elevated in smoking and various cancers.',
  1, 153),

('ca_125', 'Cancer Antigen 125',
  ARRAY['CA-125', 'CA 125'],
  'tumor_marker', 'U/mL',
  '{}'::jsonb,
  '{"male": {"low": 0, "high": 35}, "female": {"low": 0, "high": 35}}'::jsonb,
  'Glycoprotein tumor marker',
  'Elevated in ovarian cancer. Also rises in menstruation, pregnancy, endometriosis.',
  0, 154),

('ca_19_9', 'Cancer Antigen 19-9',
  ARRAY['CA-19-9', 'CA 19-9', 'CA19-9'],
  'tumor_marker', 'U/mL',
  '{}'::jsonb,
  '{"male": {"low": 0, "high": 37}, "female": {"low": 0, "high": 37}}'::jsonb,
  'Carbohydrate antigen',
  'Elevated in pancreatic, biliary, and gastrointestinal cancers.',
  0, 155),

('ca_15_3', 'Cancer Antigen 15-3',
  ARRAY['CA-15-3', 'CA 15-3', 'CA15-3'],
  'tumor_marker', 'U/mL',
  '{}'::jsonb,
  '{"male": {"low": 0, "high": 30}, "female": {"low": 0, "high": 30}}'::jsonb,
  'Mucin-type glycoprotein',
  'Used to monitor breast cancer treatment response and recurrence.',
  0, 156),

('hcg_beta', 'Beta-HCG',
  ARRAY['beta-hCG', 'B-hCG', 'human chorionic gonadotropin', 'HCG', 'pregnancy test'],
  'tumor_marker', 'mIU/mL',
  '{"IU/L": 1}'::jsonb,
  '{"male": {"low": 0, "high": 2}, "female": {"low": 0, "high": 5}}'::jsonb,
  'Hormone produced by placenta',
  'Elevated in pregnancy, gestational trophoblastic disease, and germ cell tumors.',
  1, 157),

('calcitonin', 'Calcitonin',
  ARRAY['CT', 'thyrocalcitonin'],
  'tumor_marker', 'pg/mL',
  '{"ng/L": 1}'::jsonb,
  '{"male": {"low": 0, "high": 10}, "female": {"low": 0, "high": 5}}'::jsonb,
  'Hormone from thyroid C-cells',
  'Marker for medullary thyroid carcinoma. Also elevated in MEN2 syndromes.',
  1, 158),

('thyroglobulin', 'Thyroglobulin',
  ARRAY['Tg', 'TGB'],
  'tumor_marker', 'ng/mL',
  '{"ug/L": 1}'::jsonb,
  '{"male": {"low": 0, "high": 35}, "female": {"low": 0, "high": 35}}'::jsonb,
  'Protein made by thyroid',
  'Used to monitor differentiated thyroid cancer after treatment.',
  1, 159),

-- ============================================================================
-- COAGULATION PANEL
-- ============================================================================

('pt', 'Prothrombin Time',
  ARRAY['PT', 'pro time'],
  'coagulation', 'seconds',
  '{}'::jsonb,
  '{"male": {"low": 11.0, "high": 13.5}, "female": {"low": 11.0, "high": 13.5}}'::jsonb,
  'Time for blood to clot via extrinsic pathway',
  'Prolonged in warfarin therapy, vitamin K deficiency, liver disease.',
  1, 160),

('inr', 'International Normalized Ratio',
  ARRAY['INR'],
  'coagulation', 'ratio',
  '{}'::jsonb,
  '{"male": {"low": 0.8, "high": 1.2}, "female": {"low": 0.8, "high": 1.2}}'::jsonb,
  'Standardized PT for anticoagulation monitoring',
  'Target 2.0-3.0 for most warfarin indications. Higher for mechanical valves.',
  1, 161),

('ptt', 'Partial Thromboplastin Time',
  ARRAY['PTT', 'aPTT', 'activated partial thromboplastin time'],
  'coagulation', 'seconds',
  '{}'::jsonb,
  '{"male": {"low": 25, "high": 35}, "female": {"low": 25, "high": 35}}'::jsonb,
  'Time for blood to clot via intrinsic pathway',
  'Monitors heparin therapy. Prolonged in hemophilia and factor deficiencies.',
  1, 162),

('fibrinogen', 'Fibrinogen',
  ARRAY['factor I', 'clotting factor I'],
  'coagulation', 'mg/dL',
  '{"g/L": 0.01}'::jsonb,
  '{"male": {"low": 200, "high": 400}, "female": {"low": 200, "high": 400}}'::jsonb,
  'Clotting protein converted to fibrin',
  'Low in DIC and liver disease. Elevated as acute phase reactant.',
  0, 163),

('d_dimer', 'D-Dimer',
  ARRAY['D-dimer', 'fibrin degradation product', 'FDP'],
  'coagulation', 'ng/mL',
  '{"ug/L": 1, "mg/L FEU": 0.001}'::jsonb,
  '{"male": {"low": 0, "high": 500}, "female": {"low": 0, "high": 500}}'::jsonb,
  'Fibrin degradation product',
  'Elevated in DVT, PE, DIC, and other conditions with increased fibrin turnover.',
  0, 164),

('bleeding_time', 'Bleeding Time',
  ARRAY['BT'],
  'coagulation', 'minutes',
  '{}'::jsonb,
  '{"male": {"low": 2, "high": 9}, "female": {"low": 2, "high": 9}}'::jsonb,
  'Time for bleeding to stop from standardized wound',
  'Prolonged in platelet disorders and von Willebrand disease.',
  1, 165),

('thrombin_time', 'Thrombin Time',
  ARRAY['TT'],
  'coagulation', 'seconds',
  '{}'::jsonb,
  '{"male": {"low": 14, "high": 21}, "female": {"low": 14, "high": 21}}'::jsonb,
  'Time for fibrinogen to convert to fibrin',
  'Prolonged in heparin therapy, DIC, and dysfibrinogenemia.',
  1, 166),

-- ============================================================================
-- AUTOIMMUNE MARKERS
-- ============================================================================

('ana', 'Antinuclear Antibody',
  ARRAY['ANA', 'antinuclear antibodies'],
  'autoimmune', 'titer',
  '{}'::jsonb,
  '{"male": {"low": 0, "high": 1}, "female": {"low": 0, "high": 1}}'::jsonb,
  'Antibodies against cell nucleus components',
  'Positive in lupus, Sjogren syndrome, and other autoimmune diseases. Titer 1:160+ significant.',
  0, 170),

('rheumatoid_factor', 'Rheumatoid Factor',
  ARRAY['RF', 'RA factor'],
  'autoimmune', 'IU/mL',
  '{}'::jsonb,
  '{"male": {"low": 0, "high": 15}, "female": {"low": 0, "high": 15}}'::jsonb,
  'Autoantibody against IgG',
  'Elevated in rheumatoid arthritis. Positive in 70-80% of RA patients.',
  0, 171),

('anti_ccp', 'Anti-CCP Antibodies',
  ARRAY['anti-CCP', 'anti-cyclic citrullinated peptide', 'ACPA'],
  'autoimmune', 'U/mL',
  '{}'::jsonb,
  '{"male": {"low": 0, "high": 20}, "female": {"low": 0, "high": 20}}'::jsonb,
  'Antibodies to citrullinated peptides',
  'Highly specific for rheumatoid arthritis. May appear before symptoms.',
  0, 172),

('anti_dsdna', 'Anti-dsDNA Antibodies',
  ARRAY['anti-dsDNA', 'double-stranded DNA antibody', 'anti-DNA'],
  'autoimmune', 'IU/mL',
  '{}'::jsonb,
  '{"male": {"low": 0, "high": 7}, "female": {"low": 0, "high": 7}}'::jsonb,
  'Antibodies against double-stranded DNA',
  'Highly specific for systemic lupus erythematosus (SLE).',
  0, 173),

('complement_c3', 'Complement C3',
  ARRAY['C3', 'complement component 3'],
  'autoimmune', 'mg/dL',
  '{"g/L": 0.01}'::jsonb,
  '{"male": {"low": 90, "high": 180}, "female": {"low": 90, "high": 180}}'::jsonb,
  'Complement system protein',
  'Low in active SLE, glomerulonephritis. Elevated as acute phase reactant.',
  0, 174),

('complement_c4', 'Complement C4',
  ARRAY['C4', 'complement component 4'],
  'autoimmune', 'mg/dL',
  '{"g/L": 0.01}'::jsonb,
  '{"male": {"low": 16, "high": 48}, "female": {"low": 16, "high": 48}}'::jsonb,
  'Complement system protein',
  'Low in active autoimmune disease and hereditary angioedema.',
  0, 175),

-- ============================================================================
-- PANCREATIC ENZYMES
-- ============================================================================

('amylase', 'Amylase',
  ARRAY['serum amylase', 'pancreatic amylase'],
  'pancreatic', 'U/L',
  '{"IU/L": 1}'::jsonb,
  '{"male": {"low": 28, "high": 100}, "female": {"low": 28, "high": 100}}'::jsonb,
  'Enzyme that breaks down carbohydrates',
  'Elevated 3x normal suggests acute pancreatitis. Also from salivary glands.',
  0, 180),

('lipase', 'Lipase',
  ARRAY['serum lipase', 'pancreatic lipase'],
  'pancreatic', 'U/L',
  '{"IU/L": 1}'::jsonb,
  '{"male": {"low": 0, "high": 160}, "female": {"low": 0, "high": 160}}'::jsonb,
  'Enzyme that breaks down fats',
  'More specific for pancreatitis than amylase. Elevated 3x normal diagnostic.',
  0, 181),

-- ============================================================================
-- ARTERIAL BLOOD GAS (ABG)
-- ============================================================================

('ph_blood', 'Blood pH',
  ARRAY['arterial pH', 'pH', 'blood pH'],
  'blood_gas', 'pH',
  '{}'::jsonb,
  '{"male": {"low": 7.35, "high": 7.45}, "female": {"low": 7.35, "high": 7.45}}'::jsonb,
  'Measure of blood acidity/alkalinity',
  '<7.35 is acidemia, >7.45 is alkalemia. Life-threatening outside 6.8-7.8.',
  2, 190),

('pco2', 'Partial Pressure CO2',
  ARRAY['pCO2', 'PaCO2', 'carbon dioxide partial pressure'],
  'blood_gas', 'mmHg',
  '{"kPa": 7.5}'::jsonb,
  '{"male": {"low": 35, "high": 45}, "female": {"low": 35, "high": 45}}'::jsonb,
  'Carbon dioxide tension in arterial blood',
  'High indicates respiratory acidosis (hypoventilation). Low indicates respiratory alkalosis.',
  0, 191),

('po2', 'Partial Pressure O2',
  ARRAY['pO2', 'PaO2', 'oxygen partial pressure'],
  'blood_gas', 'mmHg',
  '{"kPa": 7.5}'::jsonb,
  '{"male": {"low": 75, "high": 100}, "female": {"low": 75, "high": 100}}'::jsonb,
  'Oxygen tension in arterial blood',
  '<60 mmHg indicates respiratory failure. Lower normal at high altitude.',
  0, 192),

('base_excess', 'Base Excess',
  ARRAY['BE', 'base deficit'],
  'blood_gas', 'mEq/L',
  '{"mmol/L": 1}'::jsonb,
  '{"male": {"low": -2, "high": 2}, "female": {"low": -2, "high": 2}}'::jsonb,
  'Amount of acid/base to normalize pH',
  'Positive indicates metabolic alkalosis, negative indicates metabolic acidosis.',
  1, 193),

('oxygen_saturation', 'Oxygen Saturation',
  ARRAY['O2 sat', 'SaO2', 'SpO2', 'arterial oxygen saturation'],
  'blood_gas', '%',
  '{}'::jsonb,
  '{"male": {"low": 95, "high": 100}, "female": {"low": 95, "high": 100}}'::jsonb,
  'Percentage of hemoglobin bound to oxygen',
  '<90% indicates significant hypoxemia. Lower acceptable in COPD patients.',
  0, 194),

('lactate', 'Lactate',
  ARRAY['lactic acid', 'blood lactate'],
  'blood_gas', 'mmol/L',
  '{"mg/dL": 9.01}'::jsonb,
  '{"male": {"low": 0.5, "high": 2.0}, "female": {"low": 0.5, "high": 2.0}}'::jsonb,
  'Product of anaerobic metabolism',
  'Elevated in sepsis, shock, hypoxia, and certain metabolic disorders.',
  1, 195),

-- ============================================================================
-- URINALYSIS MARKERS
-- ============================================================================

('urine_ph', 'Urine pH',
  ARRAY['urinary pH', 'urine acidity'],
  'urinalysis', 'pH',
  '{}'::jsonb,
  '{"male": {"low": 5.0, "high": 7.0}, "female": {"low": 5.0, "high": 7.0}}'::jsonb,
  'Measure of urine acidity',
  'Influenced by diet and medications. Alkaline urine in UTI.',
  1, 200),

('specific_gravity', 'Urine Specific Gravity',
  ARRAY['SG', 'urine concentration', 'sp. gravity'],
  'urinalysis', 'ratio',
  '{}'::jsonb,
  '{"male": {"low": 1.005, "high": 1.030}, "female": {"low": 1.005, "high": 1.030}}'::jsonb,
  'Measure of urine concentration',
  'Low indicates dilute urine (overhydration). High indicates concentrated urine.',
  3, 201),

('urine_protein', 'Urine Protein',
  ARRAY['urinary protein', 'proteinuria', 'urine albumin'],
  'urinalysis', 'mg/dL',
  '{}'::jsonb,
  '{"male": {"low": 0, "high": 14}, "female": {"low": 0, "high": 14}}'::jsonb,
  'Protein in urine',
  'Elevated in kidney disease, diabetes, heart failure, and infection.',
  0, 202),

('urine_glucose', 'Urine Glucose',
  ARRAY['glucosuria', 'urinary glucose'],
  'urinalysis', 'mg/dL',
  '{}'::jsonb,
  '{"male": {"low": 0, "high": 0}, "female": {"low": 0, "high": 0}}'::jsonb,
  'Glucose in urine',
  'Normally absent. Present in diabetes when blood glucose exceeds renal threshold.',
  0, 203),

('urine_ketones', 'Urine Ketones',
  ARRAY['ketonuria', 'urinary ketones'],
  'urinalysis', 'mg/dL',
  '{}'::jsonb,
  '{"male": {"low": 0, "high": 0}, "female": {"low": 0, "high": 0}}'::jsonb,
  'Ketone bodies in urine',
  'Present in diabetic ketoacidosis, starvation, and low-carb diets.',
  0, 204),

('urine_blood', 'Urine Blood',
  ARRAY['hematuria', 'urinary blood', 'blood in urine', 'RBC urine'],
  'urinalysis', 'cells/HPF',
  '{}'::jsonb,
  '{"male": {"low": 0, "high": 2}, "female": {"low": 0, "high": 2}}'::jsonb,
  'Red blood cells in urine',
  'May indicate UTI, stones, cancer, or glomerular disease.',
  0, 205),

('urine_wbc', 'Urine WBC',
  ARRAY['pyuria', 'urinary leukocytes', 'WBC urine'],
  'urinalysis', 'cells/HPF',
  '{}'::jsonb,
  '{"male": {"low": 0, "high": 5}, "female": {"low": 0, "high": 5}}'::jsonb,
  'White blood cells in urine',
  'Elevated in urinary tract infection and inflammation.',
  0, 206),

('urine_bilirubin', 'Urine Bilirubin',
  ARRAY['bilirubinuria', 'urinary bilirubin'],
  'urinalysis', 'mg/dL',
  '{}'::jsonb,
  '{"male": {"low": 0, "high": 0}, "female": {"low": 0, "high": 0}}'::jsonb,
  'Conjugated bilirubin in urine',
  'Normally absent. Present in liver disease and biliary obstruction.',
  1, 207),

('urobilinogen', 'Urobilinogen',
  ARRAY['urine urobilinogen', 'urinary urobilinogen'],
  'urinalysis', 'EU/dL',
  '{}'::jsonb,
  '{"male": {"low": 0.1, "high": 1.0}, "female": {"low": 0.1, "high": 1.0}}'::jsonb,
  'Bilirubin breakdown product',
  'Elevated in hemolytic anemia and liver disease. Absent in complete biliary obstruction.',
  1, 208),

('urine_nitrite', 'Urine Nitrite',
  ARRAY['nitrituria', 'urinary nitrite'],
  'urinalysis', 'qualitative',
  '{}'::jsonb,
  '{"male": {"low": 0, "high": 0}, "female": {"low": 0, "high": 0}}'::jsonb,
  'Bacterial conversion of nitrate to nitrite',
  'Positive suggests bacterial UTI (gram-negative organisms).',
  0, 209),

('leukocyte_esterase', 'Leukocyte Esterase',
  ARRAY['LE', 'urine leukocyte esterase'],
  'urinalysis', 'qualitative',
  '{}'::jsonb,
  '{"male": {"low": 0, "high": 0}, "female": {"low": 0, "high": 0}}'::jsonb,
  'Enzyme from white blood cells',
  'Positive indicates WBCs in urine, suggesting infection or inflammation.',
  0, 210),

-- ============================================================================
-- ADDITIONAL SPECIALTY MARKERS
-- ============================================================================

('prealbumin', 'Prealbumin',
  ARRAY['transthyretin', 'TTR'],
  'nutrition', 'mg/dL',
  '{"g/L": 0.01}'::jsonb,
  '{"male": {"low": 20, "high": 40}, "female": {"low": 20, "high": 40}}'::jsonb,
  'Short-lived protein for nutrition assessment',
  'More sensitive to acute nutritional changes than albumin. Low in malnutrition.',
  0, 220),

('reticulocyte_count', 'Reticulocyte Count',
  ARRAY['retic count', 'reticulocytes'],
  'cbc', '%',
  '{}'::jsonb,
  '{"male": {"low": 0.5, "high": 2.5}, "female": {"low": 0.5, "high": 2.5}}'::jsonb,
  'Immature red blood cells',
  'Elevated indicates bone marrow response to anemia. Low suggests production problem.',
  1, 221),

('haptoglobin', 'Haptoglobin',
  ARRAY['Hp'],
  'hematology', 'mg/dL',
  '{"g/L": 0.01}'::jsonb,
  '{"male": {"low": 30, "high": 200}, "female": {"low": 30, "high": 200}}'::jsonb,
  'Protein that binds free hemoglobin',
  'Low in hemolytic anemia. Elevated as acute phase reactant.',
  0, 222),

('anion_gap', 'Anion Gap',
  ARRAY['AG', 'serum anion gap'],
  'electrolyte', 'mEq/L',
  '{"mmol/L": 1}'::jsonb,
  '{"male": {"low": 8, "high": 12}, "female": {"low": 8, "high": 12}}'::jsonb,
  'Difference between cations and anions',
  'Elevated in metabolic acidosis (DKA, lactic acidosis, toxins).',
  0, 223),

('osmolality_serum', 'Serum Osmolality',
  ARRAY['serum osm', 'plasma osmolality'],
  'electrolyte', 'mOsm/kg',
  '{}'::jsonb,
  '{"male": {"low": 275, "high": 295}, "female": {"low": 275, "high": 295}}'::jsonb,
  'Concentration of dissolved particles in blood',
  'Abnormal in dehydration, SIADH, diabetes insipidus.',
  0, 224),

('vitamin_c', 'Vitamin C',
  ARRAY['ascorbic acid', 'ascorbate'],
  'vitamin', 'mg/dL',
  '{"umol/L": 56.78}'::jsonb,
  '{"male": {"low": 0.4, "high": 2.0}, "female": {"low": 0.4, "high": 2.0}}'::jsonb,
  'Water-soluble antioxidant vitamin',
  'Deficiency causes scurvy. Important for collagen synthesis.',
  1, 225),

('zinc', 'Zinc',
  ARRAY['Zn', 'serum zinc'],
  'mineral', 'mcg/dL',
  '{"umol/L": 6.54}'::jsonb,
  '{"male": {"low": 60, "high": 120}, "female": {"low": 60, "high": 120}}'::jsonb,
  'Essential trace mineral',
  'Deficiency affects immune function, wound healing, and taste.',
  0, 226),

('copper', 'Copper',
  ARRAY['Cu', 'serum copper'],
  'mineral', 'mcg/dL',
  '{"umol/L": 6.355}'::jsonb,
  '{"male": {"low": 70, "high": 140}, "female": {"low": 80, "high": 155}}'::jsonb,
  'Essential trace mineral',
  'Low in Wilson disease and Menkes. High in inflammation.',
  0, 227),

('ceruloplasmin', 'Ceruloplasmin',
  ARRAY['Cp'],
  'mineral', 'mg/dL',
  '{"g/L": 0.01}'::jsonb,
  '{"male": {"low": 20, "high": 35}, "female": {"low": 20, "high": 35}}'::jsonb,
  'Copper-carrying protein',
  'Low in Wilson disease. Elevated as acute phase reactant.',
  0, 228),

('selenium', 'Selenium',
  ARRAY['Se', 'serum selenium'],
  'mineral', 'mcg/L',
  '{"umol/L": 78.96}'::jsonb,
  '{"male": {"low": 70, "high": 150}, "female": {"low": 70, "high": 150}}'::jsonb,
  'Essential trace mineral and antioxidant',
  'Deficiency linked to cardiomyopathy and thyroid dysfunction.',
  0, 229),

('parathyroid_hormone', 'Parathyroid Hormone',
  ARRAY['PTH', 'intact PTH', 'iPTH'],
  'hormone', 'pg/mL',
  '{"pmol/L": 9.43}'::jsonb,
  '{"male": {"low": 15, "high": 65}, "female": {"low": 15, "high": 65}}'::jsonb,
  'Hormone regulating calcium and phosphorus',
  'High in primary hyperparathyroidism and secondary to kidney disease.',
  0, 230),

('acth', 'Adrenocorticotropic Hormone',
  ARRAY['ACTH', 'corticotropin'],
  'hormone', 'pg/mL',
  '{"pmol/L": 4.541}'::jsonb,
  '{"male": {"low": 7, "high": 69}, "female": {"low": 6, "high": 58}}'::jsonb,
  'Pituitary hormone stimulating cortisol',
  'Used to diagnose Addison disease and Cushing syndrome.',
  0, 231),

('aldosterone', 'Aldosterone',
  ARRAY['serum aldosterone'],
  'hormone', 'ng/dL',
  '{"pmol/L": 0.0361}'::jsonb,
  '{"male": {"low": 3, "high": 16}, "female": {"low": 3, "high": 16}}'::jsonb,
  'Hormone regulating sodium and potassium',
  'Elevated in primary aldosteronism. Varies with posture.',
  0, 232),

('renin', 'Renin Activity',
  ARRAY['plasma renin activity', 'PRA'],
  'hormone', 'ng/mL/hr',
  '{}'::jsonb,
  '{"male": {"low": 0.5, "high": 3.0}, "female": {"low": 0.5, "high": 3.0}}'::jsonb,
  'Enzyme in blood pressure regulation',
  'Used with aldosterone to diagnose adrenal disorders.',
  1, 233),

('nt_probnp_age_adjusted', 'NT-proBNP (Age-Adjusted)',
  ARRAY['age-adjusted NT-proBNP'],
  'cardiac', 'pg/mL',
  '{"ng/L": 1}'::jsonb,
  '{"male": {"low": 0, "high": 300}, "female": {"low": 0, "high": 300}}'::jsonb,
  'Heart failure marker with age consideration',
  'Normal cutoffs increase with age: <50y: <450, 50-75y: <900, >75y: <1800.',
  0, 234),

('myoglobin', 'Myoglobin',
  ARRAY['Mb', 'serum myoglobin'],
  'cardiac', 'ng/mL',
  '{"ug/L": 1}'::jsonb,
  '{"male": {"low": 25, "high": 72}, "female": {"low": 25, "high": 58}}'::jsonb,
  'Oxygen-binding muscle protein',
  'Early marker of MI but not specific. Also elevated in muscle injury.',
  0, 235),

('ammonia', 'Ammonia',
  ARRAY['blood ammonia', 'NH3', 'plasma ammonia'],
  'liver', 'umol/L',
  '{"ug/dL": 1.7}'::jsonb,
  '{"male": {"low": 15, "high": 45}, "female": {"low": 15, "high": 45}}'::jsonb,
  'Metabolic waste from protein breakdown',
  'Elevated in liver failure and can cause hepatic encephalopathy.',
  0, 236),

('anti_tpo', 'Anti-TPO Antibodies',
  ARRAY['anti-TPO', 'thyroid peroxidase antibodies', 'TPOAb'],
  'autoimmune', 'IU/mL',
  '{}'::jsonb,
  '{"male": {"low": 0, "high": 34}, "female": {"low": 0, "high": 34}}'::jsonb,
  'Antibodies against thyroid peroxidase',
  'Elevated in Hashimoto thyroiditis and Graves disease.',
  0, 237),

('anti_thyroglobulin', 'Anti-Thyroglobulin Antibodies',
  ARRAY['TgAb', 'anti-Tg', 'thyroglobulin antibodies'],
  'autoimmune', 'IU/mL',
  '{}'::jsonb,
  '{"male": {"low": 0, "high": 40}, "female": {"low": 0, "high": 40}}'::jsonb,
  'Antibodies against thyroglobulin',
  'Elevated in autoimmune thyroid disease. May interfere with thyroglobulin testing.',
  0, 238);
